list_procedures_flow = {
    '1': 'PRC_CARGA_TB_DIM_DATA'
    ,'2': 'PRC_CARGA_TB_AUXEMERGENCIAL_MUNICIPIOS'
    ,'3': 'PRC_CARGA_TB_AUXEMERGENCIAL_BENEFICIOS'
    ,'4': 'PRC_CARGA_TB_AUXEMERGENCIAL_BENEFICIOS_POR_ENQUADRAMENTO'
    ,'5': 'PRC_CARGA_TB_AUXEMERGENCIAL_BENEFICIADOS'
    ,'6': 'PRC_INSERT_BASE_MUNICIPIOS'
    ,'7': 'PRC_LIMPA_STG_AUXEMERGENCIAL'
}
