CREATE DATABASE [GOVBR]
GO

USE [GOVBR]
GO

CREATE TABLE [TB_AUXEMERGENCIAL_MUNICIPIOS]
(
	[NR_ID] INT IDENTITY(1,1) PRIMARY KEY
	,[NR_COD_MUNICIPIO] BIGINT NOT NULL
	,[NM_NOME_MUNICIPIO] VARCHAR(50) NOT NULL
	,[NM_UF] VARCHAR(2) NOT NULL
)WITH(DATA_COMPRESSION=PAGE)
CREATE INDEX IDX_AUXEMERGENCIAL_MUNICIPIOS_NR_COD_MUNICIPIO ON TB_AUXEMERGENCIAL_MUNICIPIOS (NR_COD_MUNICIPIO)
GO

CREATE TABLE [TB_AUXEMERGENCIAL_BENEFICIADOS](
	[NR_ID] INT PRIMARY KEY IDENTITY(1,1)
	,[NM_ANO] VARCHAR(4) NOT NULL
	,[NM_MES] VARCHAR(2) NOT NULL
	,[NR_COD_MUNICIPIO] BIGINT NOT NULL
	,[NR_TOTAL_REGISTRADOS] BIGINT NULL
	,[NR_TOTAL_ANONIMOS] BIGINT NULL
)WITH(DATA_COMPRESSION=PAGE)
CREATE INDEX AUXEMERGENCIAL_BENEFICIADOS_NM_ANO_MES ON TB_AUXEMERGENCIAL_BENEFICIADOS (NM_ANO, NM_MES)
GO

CREATE TABLE [TB_AUXEMERGENCIAL_BENEFICIOS](
	[NR_ID] INT PRIMARY KEY IDENTITY(1,1)
	,[NM_ANO] VARCHAR(4) NOT NULL
	,[NM_MES] VARCHAR(2) NOT NULL
	,[NR_COD_MUNICIPIO] BIGINT NOT NULL
	,[NM_ENQUADRAMENTO] VARCHAR(15) NOT NULL
	,[NR_PARCELA] INT NOT NULL
	,[NR_TOTAL_PAGO] DECIMAL(15,5) NOT NULL
)WITH(DATA_COMPRESSION=PAGE)
CREATE INDEX AUXEMERGENCIAL_BENEFICIOS_NM_ANO_MES ON TB_AUXEMERGENCIAL_BENEFICIOS (NM_ANO, NM_MES)
GO


CREATE PROCEDURE PRC_CARGA_TB_AUXEMERGENCIAL_MUNICIPIOS AS
BEGIN
    INSERT INTO [TB_AUXEMERGENCIAL_MUNICIPIOS]
	SELECT DISTINCT
		[COD_MUNICIPIO]
		,[NOME_MUNICIPIO]
		,[UF]
	FROM [TB_STG_AUXEMERGENCIAL_MUNICIPIOS]
	WHERE [COD_MUNICIPIO] NOT IN (SELECT [NR_COD_MUNICIPIO] 
									FROM [TB_AUXEMERGENCIAL_MUNICIPIOS]
								 )
END
GO

CREATE PROCEDURE PRC_CARGA_TB_AUXEMERGENCIAL_BENEFICIOS AS
BEGIN
	DECLARE @ANO VARCHAR(4), @MES VARCHAR(2)
	SET @ANO = (SELECT DISTINCT TOP 1 LEFT([ANO_MES],4) FROM [TB_STG_AUXEMERGENCIAL_BENEFICIOS])
	SET @MES = (SELECT DISTINCT TOP 1 RIGHT([ANO_MES],2) FROM [TB_STG_AUXEMERGENCIAL_BENEFICIOS])

	DELETE FROM [TB_AUXEMERGENCIAL_BENEFICIOS]
	WHERE [NM_ANO] = @ANO AND [NM_MES] = @MES
	
	INSERT INTO [TB_AUXEMERGENCIAL_BENEFICIOS]
	SELECT
		LEFT([ANO_MES],4) AS ANO
		,RIGHT([ANO_MES],2) AS MES
        ,[COD_MUNICIPIO]
        ,[ENQUADRAMENTO]
        ,REPLACE([PARCELA],'ª','') AS PARCELA
        ,CAST([TOTAL_PAGO] AS DECIMAL(15,5)) AS TOTAL_PAGO
	FROM [TB_STG_AUXEMERGENCIAL_BENEFICIOS]
	WHERE [ANO_MES] = CONCAT(@ANO,@MES)
END
GO

CREATE PROCEDURE PRC_CARGA_TB_AUXEMERGENCIAL_BENEFICIADOS AS
BEGIN
	IF OBJECT_ID(N'tempdb..#MUNICIPIOS_BENEFICIADOS', N'U') IS NOT NULL BEGIN DROP TABLE #MUNICIPIOS_BENEFICIADOS END
	SELECT
		LEFT([ANO_MES],4) AS ANO
		,RIGHT([ANO_MES],2) AS MES
		,[COD_MUNICIPIO]
	INTO #MUNICIPIOS_BENEFICIADOS
	FROM [TB_STG_AUXEMERGENCIAL_BENEFICIADOS_REGISTRADOS]

	UNION ALL

	SELECT 
		LEFT([ANO_MES],4) AS ANO
		,RIGHT([ANO_MES],2) AS MES
		,[COD_MUNICIPIO]
	FROM [TB_STG_AUXEMERGENCIAL_BENEFICIADOS_ANONIMOS]


	INSERT INTO [TB_AUXEMERGENCIAL_BENEFICIADOS](
		[NM_ANO]
		,[NM_MES]
		,[NR_COD_MUNICIPIO]
	)
	SELECT DISTINCT
		A.[ANO]
		,A.[MES]
		,A.[COD_MUNICIPIO]
	FROM #MUNICIPIOS_BENEFICIADOS A
	LEFT JOIN [TB_AUXEMERGENCIAL_BENEFICIADOS] B
	ON B.[NR_COD_MUNICIPIO] = A.[COD_MUNICIPIO]
	AND B.[NM_ANO] = A.[ANO] AND B.[NM_MES]=A.[MES]
	WHERE B.[NR_COD_MUNICIPIO] IS NULL

    IF OBJECT_ID(N'tempdb..#MUNICIPIOS_BENEFICIADOS', N'U') IS NOT NULL BEGIN DROP TABLE #MUNICIPIOS_BENEFICIADOS END

	UPDATE A 
	SET [NR_TOTAL_REGISTRADOS] = ISNULL(B.[TOTAL_BENEF],0)
	FROM [TB_AUXEMERGENCIAL_BENEFICIADOS] A
	LEFT JOIN [TB_STG_AUXEMERGENCIAL_BENEFICIADOS_REGISTRADOS] B
	ON B.[COD_MUNICIPIO]=A.[NR_COD_MUNICIPIO]
	AND B.[ANO_MES]=CONCAT(A.[NM_ANO],A.[NM_MES])

	UPDATE A
	SET [NR_TOTAL_ANONIMOS] = ISNULL(B.[TOTAL_ANONIMOS],0)
	FROM [TB_AUXEMERGENCIAL_BENEFICIADOS] A
	LEFT JOIN [TB_STG_AUXEMERGENCIAL_BENEFICIADOS_ANONIMOS] B
	ON B.[COD_MUNICIPIO]=A.[NR_COD_MUNICIPIO]
	AND B.[ANO_MES]=CONCAT(A.[NM_ANO],A.[NM_MES])
END
GO

CREATE PROCEDURE PRC_LIMPA_STG_AUXEMERGENCIAL AS
BEGIN
	TRUNCATE TABLE [TB_STG_AUXEMERGENCIAL_MUNICIPIOS]
	TRUNCATE TABLE [TB_STG_AUXEMERGENCIAL_BENEFICIOS]
	TRUNCATE TABLE [TB_STG_AUXEMERGENCIAL_BENEFICIADOS_ANONIMOS]
	TRUNCATE TABLE [TB_STG_AUXEMERGENCIAL_BENEFICIADOS_REGISTRADOS]
END
GO

CREATE VIEW VW_TOTAL_BENEFICIADOS_POR_UF AS
SELECT BENEF.[NM_ANO]
		,BENEF.[NM_MES]
		,MUN.[NM_UF]
		,SUM(BENEF.[NR_TOTAL_REGISTRADOS]) AS NR_TOTAL_REGISTRADOS
		,SUM(BENEF.[NR_TOTAL_ANONIMOS]) AS NR_TOTAL_ANONIMOS
		,SUM(BENEF.[NR_TOTAL_REGISTRADOS])+SUM(BENEF.[NR_TOTAL_ANONIMOS]) AS NR_TOTAL_BENEFICIADOS
FROM [TB_AUXEMERGENCIAL_BENEFICIADOS] BENEF WITH(READPAST)
LEFT JOIN [TB_AUXEMERGENCIAL_MUNICIPIOS] MUN WITH(READPAST)
ON MUN.[NR_COD_MUNICIPIO]=BENEF.[NR_COD_MUNICIPIO]
GROUP BY BENEF.[NM_ANO],BENEF.[NM_MES],MUN.[NM_UF]
GO